# Generated by Django 4.2.1 on 2023-06-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myusers_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/%y/%m/%d'),
        ),
    ]
