# Generated by Django 4.2.1 on 2023-06-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0002_poste_image_alter_relation_from_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poste',
            old_name='Image',
            new_name='image',
        ),
    ]
