# Generated by Django 4.2.1 on 2023-06-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_otpmodel_onetimecode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onetimecode',
            options={'get_latest_by': 'created'},
        ),
    ]
