# Generated by Django 4.2.1 on 2023-06-12 11:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0004_direct_reply_directs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direct_reply',
        ),
        migrations.AlterField(
            model_name='poste',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
