from django.contrib import admin
from django.urls import path, include
from A_Django import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

# Define the URL patterns for the project
urlpatterns = [
    # Admin site URL
    path('admin/', admin.site.urls),

    # Include the URLs from the 'home' app with the 'home' namespace
    path('', include('home.urls', namespace='home')),

    # Include the URLs from the 'accounts' app with the 'accounts' namespace
    path("accounts/", include('accounts.urls', namespace='accounts')),

    # Include the URLs from the 'proof' app with the 'proof' namespace
    path('profile/', include('proof.urls', namespace='proof')),

    # Endpoint to serve the API schema generated by drf_spectacular
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/',SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/',SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
