# Generated by Django 4.2.1 on 2023-06-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='picture',
            field=models.ImageField(upload_to='profile/%y/%m/%d'),
        ),
    ]
